apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: efksuysqt-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:22e44e8e55c66321e75f14fe8436ee49c5c43552@sha256:4bd84dcf2c74869709593a33773a8b7281f2669a48ac64e71c2823b0c67c4def
          name: container-image
